﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace Winequality_red_Console
{
    public partial class Winequality_red
    {
        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"fixed acidity", @"fixed acidity"),new InputOutputColumnPair(@"volatile acidity", @"volatile acidity"),new InputOutputColumnPair(@"citric acid", @"citric acid"),new InputOutputColumnPair(@"residual sugar", @"residual sugar"),new InputOutputColumnPair(@"chlorides", @"chlorides"),new InputOutputColumnPair(@"free sulfur dioxide", @"free sulfur dioxide"),new InputOutputColumnPair(@"total sulfur dioxide", @"total sulfur dioxide"),new InputOutputColumnPair(@"density", @"density"),new InputOutputColumnPair(@"pH", @"pH"),new InputOutputColumnPair(@"sulphates", @"sulphates"),new InputOutputColumnPair(@"alcohol", @"alcohol")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"fixed acidity",@"volatile acidity",@"citric acid",@"residual sugar",@"chlorides",@"free sulfur dioxide",@"total sulfur dioxide",@"density",@"pH",@"sulphates",@"alcohol"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(outputColumnName:@"quality",inputColumnName:@"quality"))      
                                    .Append(mlContext.MulticlassClassification.Trainers.OneVersusAll(binaryEstimator:mlContext.BinaryClassification.Trainers.FastTree(new FastTreeBinaryTrainer.Options(){NumberOfLeaves=736,MinimumExampleCountPerLeaf=54,NumberOfTrees=184,MaximumBinCountPerFeature=30,FeatureFraction=0.99999999,LearningRate=0.0464119637116949,LabelColumnName=@"quality",FeatureColumnName=@"Features"}),labelColumnName: @"quality"))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(outputColumnName:@"PredictedLabel",inputColumnName:@"PredictedLabel"));

            return pipeline;
        }
    }
}
