// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Et_example_Console
{
    public partial class Et_example
    {
        /// <summary>
        /// model input class for Et_example.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"date")]
            public string Date { get; set; }

            [ColumnName(@"precipitation")]
            public float Precipitation { get; set; }

            [ColumnName(@"temp_max")]
            public float Temp_max { get; set; }

            [ColumnName(@"temp_min")]
            public float Temp_min { get; set; }

            [ColumnName(@"wind")]
            public float Wind { get; set; }

            [ColumnName(@"weather")]
            public string Weather { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for Et_example.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"date")]
            public float[] Date { get; set; }

            [ColumnName(@"precipitation")]
            public float Precipitation { get; set; }

            [ColumnName(@"temp_max")]
            public float Temp_max { get; set; }

            [ColumnName(@"temp_min")]
            public float Temp_min { get; set; }

            [ColumnName(@"wind")]
            public float Wind { get; set; }

            [ColumnName(@"weather")]
            public uint Weather { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("Et_example.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
