﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace Et_example_Console
{
    public partial class Et_example
    {
        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"precipitation", @"precipitation"),new InputOutputColumnPair(@"temp_max", @"temp_max"),new InputOutputColumnPair(@"temp_min", @"temp_min"),new InputOutputColumnPair(@"wind", @"wind")})      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"date",outputColumnName:@"date"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"precipitation",@"temp_max",@"temp_min",@"wind",@"date"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(outputColumnName:@"weather",inputColumnName:@"weather"))      
                                    .Append(mlContext.MulticlassClassification.Trainers.OneVersusAll(binaryEstimator:mlContext.BinaryClassification.Trainers.FastTree(new FastTreeBinaryTrainer.Options(){NumberOfLeaves=23,MinimumExampleCountPerLeaf=7,NumberOfTrees=4,MaximumBinCountPerFeature=468,FeatureFraction=0.643759314900262,LearningRate=0.0441294258105961,LabelColumnName=@"weather",FeatureColumnName=@"Features"}),labelColumnName: @"weather"))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(outputColumnName:@"PredictedLabel",inputColumnName:@"PredictedLabel"));

            return pipeline;
        }
    }
}
