
// This file was auto-generated by ML.NET Model Builder. 

using Rain_Console;

// Create single instance of sample data from first line of dataset for model input
Rain.ModelInput sampleData = new Rain.ModelInput()
{
    Date = @"2015-01-02",
    Temp = 28F,
    Inflation = 0.052F,
    Friday = 1F,
    Saturday = 0F,
    Sunday = 0F,
    Thursday = 0F,
    Tuesday = 0F,
    Wednesday = 0F,
    Annul_Closing_of_Accounts_Day = 0F,
    Babu_Jagjivan_Ram_Jayanti = 0F,
    Bakrid___Eid_al_Adha = 0F,
    Christmas_Day = 0F,
    Diwali = 0F,
    Dr_Ambedkar_Jayanti = 0F,
    Eid_e_Milad = 0F,
    Gandhi_Jayanti = 0F,
    Ganesh_Chaturthi = 0F,
    Good_Friday = 0F,
    Holi = 0F,
    Idul_Fitr = 0F,
    Independence_Day = 0F,
    Janmashtami = 0F,
    Kanuma_Panduga = 0F,
    Maha_Ashtami = 0F,
    Maha_Shivaratri = 0F,
    Makar_Sankranti = 0F,
    Muharram = 0F,
    Pongal = 0F,
    Ram_Navami = 0F,
    Republic_Day = 0F,
    Ugadi = 0F,
    Vijaya_Dashami = 0F,
    Energy_Required__MU_ = 135.684F,
};

// Make a single prediction on the sample data and print results
var predictionResult = Rain.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Rain with predicted Rain from sample data...\n\n");


Console.WriteLine($"Date: {@"2015-01-02"}");
Console.WriteLine($"Temp: {28F}");
Console.WriteLine($"Rain: {0.4F}");
Console.WriteLine($"Inflation: {0.052F}");
Console.WriteLine($"Friday: {1F}");
Console.WriteLine($"Saturday: {0F}");
Console.WriteLine($"Sunday: {0F}");
Console.WriteLine($"Thursday: {0F}");
Console.WriteLine($"Tuesday: {0F}");
Console.WriteLine($"Wednesday: {0F}");
Console.WriteLine($"Annul_Closing_of_Accounts_Day: {0F}");
Console.WriteLine($"Babu_Jagjivan_Ram_Jayanti: {0F}");
Console.WriteLine($"Bakrid___Eid_al_Adha: {0F}");
Console.WriteLine($"Christmas_Day: {0F}");
Console.WriteLine($"Diwali: {0F}");
Console.WriteLine($"Dr_Ambedkar_Jayanti: {0F}");
Console.WriteLine($"Eid_e_Milad: {0F}");
Console.WriteLine($"Gandhi_Jayanti: {0F}");
Console.WriteLine($"Ganesh_Chaturthi: {0F}");
Console.WriteLine($"Good_Friday: {0F}");
Console.WriteLine($"Holi: {0F}");
Console.WriteLine($"Idul_Fitr: {0F}");
Console.WriteLine($"Independence_Day: {0F}");
Console.WriteLine($"Janmashtami: {0F}");
Console.WriteLine($"Kanuma_Panduga: {0F}");
Console.WriteLine($"Maha_Ashtami: {0F}");
Console.WriteLine($"Maha_Shivaratri: {0F}");
Console.WriteLine($"Makar_Sankranti: {0F}");
Console.WriteLine($"Muharram: {0F}");
Console.WriteLine($"Pongal: {0F}");
Console.WriteLine($"Ram_Navami: {0F}");
Console.WriteLine($"Republic_Day: {0F}");
Console.WriteLine($"Ugadi: {0F}");
Console.WriteLine($"Vijaya_Dashami: {0F}");
Console.WriteLine($"Energy_Required__MU_: {135.684F}");


Console.WriteLine($"\n\nPredicted Rain: {predictionResult.Score}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

