// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Rain_Console
{
    public partial class Rain
    {
        /// <summary>
        /// model input class for Rain.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Date")]
            public string Date { get; set; }

            [ColumnName(@"temp")]
            public float Temp { get; set; }

            [ColumnName(@"rain")]
            public float Rain { get; set; }

            [ColumnName(@"inflation")]
            public float Inflation { get; set; }

            [ColumnName(@"Friday")]
            public float Friday { get; set; }

            [ColumnName(@"Saturday")]
            public float Saturday { get; set; }

            [ColumnName(@"Sunday")]
            public float Sunday { get; set; }

            [ColumnName(@"Thursday")]
            public float Thursday { get; set; }

            [ColumnName(@"Tuesday")]
            public float Tuesday { get; set; }

            [ColumnName(@"Wednesday")]
            public float Wednesday { get; set; }

            [ColumnName(@"Annul Closing of Accounts Day")]
            public float Annul_Closing_of_Accounts_Day { get; set; }

            [ColumnName(@"Babu Jagjivan Ram Jayanti")]
            public float Babu_Jagjivan_Ram_Jayanti { get; set; }

            [ColumnName(@"Bakrid / Eid al Adha")]
            public float Bakrid___Eid_al_Adha { get; set; }

            [ColumnName(@"Christmas Day")]
            public float Christmas_Day { get; set; }

            [ColumnName(@"Diwali")]
            public float Diwali { get; set; }

            [ColumnName(@"Dr Ambedkar Jayanti")]
            public float Dr_Ambedkar_Jayanti { get; set; }

            [ColumnName(@"Eid e Milad")]
            public float Eid_e_Milad { get; set; }

            [ColumnName(@"Gandhi Jayanti")]
            public float Gandhi_Jayanti { get; set; }

            [ColumnName(@"Ganesh Chaturthi")]
            public float Ganesh_Chaturthi { get; set; }

            [ColumnName(@"Good Friday")]
            public float Good_Friday { get; set; }

            [ColumnName(@"Holi")]
            public float Holi { get; set; }

            [ColumnName(@"Idul Fitr")]
            public float Idul_Fitr { get; set; }

            [ColumnName(@"Independence Day")]
            public float Independence_Day { get; set; }

            [ColumnName(@"Janmashtami")]
            public float Janmashtami { get; set; }

            [ColumnName(@"Kanuma Panduga")]
            public float Kanuma_Panduga { get; set; }

            [ColumnName(@"Maha Ashtami")]
            public float Maha_Ashtami { get; set; }

            [ColumnName(@"Maha Shivaratri")]
            public float Maha_Shivaratri { get; set; }

            [ColumnName(@"Makar Sankranti")]
            public float Makar_Sankranti { get; set; }

            [ColumnName(@"Muharram")]
            public float Muharram { get; set; }

            [ColumnName(@"Pongal")]
            public float Pongal { get; set; }

            [ColumnName(@"Ram Navami")]
            public float Ram_Navami { get; set; }

            [ColumnName(@"Republic Day")]
            public float Republic_Day { get; set; }

            [ColumnName(@"Ugadi")]
            public float Ugadi { get; set; }

            [ColumnName(@"Vijaya Dashami")]
            public float Vijaya_Dashami { get; set; }

            [ColumnName(@"Energy Required (MU)")]
            public float Energy_Required__MU_ { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for Rain.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Date")]
            public float[] Date { get; set; }

            [ColumnName(@"temp")]
            public float Temp { get; set; }

            [ColumnName(@"rain")]
            public float Rain { get; set; }

            [ColumnName(@"inflation")]
            public float Inflation { get; set; }

            [ColumnName(@"Friday")]
            public float Friday { get; set; }

            [ColumnName(@"Saturday")]
            public float Saturday { get; set; }

            [ColumnName(@"Sunday")]
            public float Sunday { get; set; }

            [ColumnName(@"Thursday")]
            public float Thursday { get; set; }

            [ColumnName(@"Tuesday")]
            public float Tuesday { get; set; }

            [ColumnName(@"Wednesday")]
            public float Wednesday { get; set; }

            [ColumnName(@"Annul Closing of Accounts Day")]
            public float Annul_Closing_of_Accounts_Day { get; set; }

            [ColumnName(@"Babu Jagjivan Ram Jayanti")]
            public float Babu_Jagjivan_Ram_Jayanti { get; set; }

            [ColumnName(@"Bakrid / Eid al Adha")]
            public float Bakrid___Eid_al_Adha { get; set; }

            [ColumnName(@"Christmas Day")]
            public float Christmas_Day { get; set; }

            [ColumnName(@"Diwali")]
            public float Diwali { get; set; }

            [ColumnName(@"Dr Ambedkar Jayanti")]
            public float Dr_Ambedkar_Jayanti { get; set; }

            [ColumnName(@"Eid e Milad")]
            public float Eid_e_Milad { get; set; }

            [ColumnName(@"Gandhi Jayanti")]
            public float Gandhi_Jayanti { get; set; }

            [ColumnName(@"Ganesh Chaturthi")]
            public float Ganesh_Chaturthi { get; set; }

            [ColumnName(@"Good Friday")]
            public float Good_Friday { get; set; }

            [ColumnName(@"Holi")]
            public float Holi { get; set; }

            [ColumnName(@"Idul Fitr")]
            public float Idul_Fitr { get; set; }

            [ColumnName(@"Independence Day")]
            public float Independence_Day { get; set; }

            [ColumnName(@"Janmashtami")]
            public float Janmashtami { get; set; }

            [ColumnName(@"Kanuma Panduga")]
            public float Kanuma_Panduga { get; set; }

            [ColumnName(@"Maha Ashtami")]
            public float Maha_Ashtami { get; set; }

            [ColumnName(@"Maha Shivaratri")]
            public float Maha_Shivaratri { get; set; }

            [ColumnName(@"Makar Sankranti")]
            public float Makar_Sankranti { get; set; }

            [ColumnName(@"Muharram")]
            public float Muharram { get; set; }

            [ColumnName(@"Pongal")]
            public float Pongal { get; set; }

            [ColumnName(@"Ram Navami")]
            public float Ram_Navami { get; set; }

            [ColumnName(@"Republic Day")]
            public float Republic_Day { get; set; }

            [ColumnName(@"Ugadi")]
            public float Ugadi { get; set; }

            [ColumnName(@"Vijaya Dashami")]
            public float Vijaya_Dashami { get; set; }

            [ColumnName(@"Energy Required (MU)")]
            public float Energy_Required__MU_ { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("rain.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
